server:
  port: 8093
  compression:
    enabled: true
  
management:
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP

spring:
  application:
    name: apollo-portal
  datasource:
    url: jdbc:mysql://localhost:3306/ApolloPortalDB?autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
ctrip:
     appid: 100003173
logging:
        file: /opt/logs/100003171/apollo-configservice.log
env: dev
#dev_meta: http://127.0.0.1:8091
